const MAX_INTEGER = 90000000000;
const SUBSCRIPTIONS_STEP = 100;
const ITEMS_STEP = 20;
const SIZE_STEP = 1000;
export default {
    WL_PATH_DELIMITER: '--',
    // Storage
    REDUX_STORE_NAME: 'sto',
    DEMO_REDUX_STORE_NAME: 'std',
    GAME_STATE_NAME: 'gst',
    DEMO_GAME_STATE_NAME: 'dst',
    UDIC_GAME_STATE_NAME: 'ust',
    STUFF_NAME: 'stu',
    DEMO_STUFF_NAME: 'dtu',
    UDIC_STUFF_NAME: 'utu',
    // 
    PADDED_TIMESTAMP_LEN: 14,
    PADDED_USERID_LEN: 12,
    
    // Actions
    CHANGE_UPDATING_STATE: "CHANGE_UPDATING_STATE",
    CHANGE_SELECTED_TAB: "CHANGE_SELECTED_TAB",
    HANDLE_DRAWER: "HANDLE_DRAWER",
    EXCLUDE_DIC_ITEM: "EXCLUDE_DIC_ITEM", 
    INCLUDE_DIC_ITEM: "INCLUDE_DIC_ITEM",
    ADD_DIC_ITEM: "ADD_DIC_ITEM",
    REMOVE_DIC_ITEM: "REMOVE_DIC_ITEM",
    // CHANGE_ORDER_BY: "CHANGE_ORDER_BY",
    // CHANGE_ORDER: "CHANGE_ORDER",
    CHANGE_ORDERS: "CHANGE_ORDERS",
    CHANGE_ROWS_PER_PAGE: "CHANGE_ROWS_PER_PAGE",
    CHANGE_PAGE: "CHANGE_PAGE",
    CHANGE_LEARNED_LANG: "CHANGE_LEARNED_LANG", 
    CHANGE_MOTHER_LANG: "CHANGE_MOTHER_LANG",
    CHANGE_INTERFACE_LANG: "CHANGE_INTERFACE_LANG",
    CHANGE_USER: "CHANGE_USER",
    CHANGE_USER_DIC_SELECTED: "CHANGE_USER_DIC_SELECTED",
    CHANGE_ITEMS: "CHANGE_ITEMS",
    CHANGE_ALTITEMS: "CHANGE_ALTITEMS",
    CHANGE_ENTIRE_STATE: "CHANGE_ENTIRE_STATE",
    // Word list file 
    MAX_DIC_FILE_SIZE: 0x100000, // 0x300000 — 3 145 728, 0x100000 — 1048576
    // Table for word list
    MAX_WORDLIST_TABLE_STRLEN: 80,
    //
    SCOPE_COUNT_VALUE:1,
    // Wordlist filter limits constants
    subscriptionsMinProps: {min: 0, max: MAX_INTEGER-SUBSCRIPTIONS_STEP, step: SUBSCRIPTIONS_STEP},
    subscriptionsMaxProps: {min: SUBSCRIPTIONS_STEP, max: MAX_INTEGER, step: SUBSCRIPTIONS_STEP},
    itemsMinProps: {min: 0, max: MAX_INTEGER-ITEMS_STEP, step: ITEMS_STEP},
    itemsMaxProps: {min: ITEMS_STEP, max: MAX_INTEGER, step: ITEMS_STEP},
    sizeMinProps: {min: 0, max: MAX_INTEGER-SIZE_STEP, step: SIZE_STEP},
    sizeMaxProps: {min: SIZE_STEP, max: MAX_INTEGER, step: SIZE_STEP},
    // subspects cache
    SUBSPECS_OBSOLETE_PERIOD: 600000,
    // wordlist cache
    WORDLIST_OBSOLETE_PERIOD: 1200000,
    // user timestamp difference
    USER_OBSOLETE_DIFFERENCE: 600000,
    // HTTP request retcode constants
    RETCODE_OK: 'O', RETCODE_ERROR: 0,
    };


